#服务配置
server:
  port: 9000
#spring配置
spring:
  #1.应用配置
  application:
    name: qm-system #指定服务名
  #2.数据库连接池
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/em?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  #3.JPA
  jpa:
    database: MySQL
    show-sql: false
    open-in-view: true

base-qm-cfg:
  stat-num: 50
  group_num: 10
  workshop_num: 2

global:
  user:
    time: 604800
